### ISSUE TITLE
jest test broken with your approach

### ISSUE THREAD

**Issue by carvajalluis** [kunokdev/cra-runtime-environment-variables#1]
It seems awesome that I can have runtime environment variables but to my surprise many of my tests stopped working because they seem to be unable to find `window._env_ ` while running `react-scripts test`are you experiencing similar issues?

**Comment by kunokdev** [comment]
Hello, could you try something like this:
```
const window = global;
window._env_ = {
  API_URL: "https://github.com"
};
```
I've commited to this file for example: https://github.com/kunokdev/cra-runtime-environment-variables/blob/master/src/App.test.js

Let me know if this helped you, otherwise we will figure something else for your case.

**Comment by kunokdev** [comment]
Assuming this should work, closing. Comment if you still have issues, then we will reopen this issue.

**Comment by carvajalluis** [comment]
Hey, thanks. since my project is kind of in a hurry we went ahead and removed those tests for now.  when we run into it again I will try this.

**Comment by sfoxall** [comment]
Hi

I am getting a similar issue, I get this error:

`TypeError: Cannot read properties of undefined (reading 'ENVIRONMENT')`

How can I set the environment when using the render function from the testing-library? 

sample code:

```import React from 'react';
import { render } from '@testing-library/react';
import App from '../App';

// Tests require environment variables to be set
const window = global
window._env_ = {
    ENVIRONMENT: "dev",
};

test('Title test', () => {
    const { getByText } = render(<App />);
    const titleElement = getByText(/Title/i);
    expect(titleElement).toBeInTheDocument();
});
