### ISSUE TITLE
[Question/Discussion]: Any thoughts on proxying?

### ISSUE THREAD

**Issue by wmik** [kunokdev/cra-runtime-environment-variables#10]
Hi!
Great post! 🎉 

It kind of got me thinking... 🤔 
So, instead of creating an environment variable file and adding an extra import,
what if you proxy the request from a static endpoint on the front end to the actual url using nginx?

**`nginx.conf`**
```diff
server {
  listen 80;
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
    expires -1; # Set it to different value depending on your standard requirements
  }
+  location /api {
+  proxy_pass /actual/api/url;
+  proxy_set_header HOST $host;
+  proxy_set_header X-Real-IP $remote_addr;
+ }
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
```

Now all requests made to `/api` endpoint are _"forwarded"_ to the actual url.

This is definitely a specific use case for urls so I can't say that much about other runtime environment variables you may want to inject into the dom.

Any thoughts on this?

**Comment by kunokdev** [comment]
Sounds really cool but there is so many other type of environment variables such as public keys, client id, etc... and then this would not cover it.
