### ISSUE TITLE
[Question] how docker -e variables will go to .env file?

### ISSUE THREAD

**Issue by changsijay** [kunokdev/cra-runtime-environment-variables#11]
Hi, thanks for sharing the article in freecodecamp,
There is one point I got confused,

> docker run -p 3000:80 -e API_URL=https://staging.api.com -t kunokdev/cra-runtime-environment-variables

How can this(-e option) change `.env` file content for `env.sh` to get/parse the runtime variable?

By the way,
I changed this part by overriding  the `.env` file, use `-v`
```
-v .env:/usr/share/nginx/html/.env
```

**Comment by kunokdev** [comment]
`-e` can't change contents of `.env` file, changing list of possible environment variables should be done as part of build time, not runtime, this repository focuses on injecting values on runtime rather than allowing changing list of possible environment variables.
