### ISSUE TITLE
How can i add a health check route ?

### ISSUE THREAD

**Issue by dileepthomas** [kunokdev/cra-runtime-environment-variables#14]
tried adding like this in default.conf, but didn't worked, Is it because of the node:alpine version. I have found a similar one but how can i add this health check to this default.conf 

https://stackoverflow.com/questions/50295614/nginx-status-endpoint-running-inside-docker

Is it possible. And many thanks for the article it will be a great help on how to add health check ?

server{
  location /health {
        return 200 "healthy\n";
  }
}

**Comment by kunokdev** [comment]
Closing since this issue is old and not directly related to the repository as you may use any ngnix config which satisfies your needs. Config from this repository is just minimal working example, any addition to it is allowed, it won't affect the way env vars are injected into runtime.
