### ISSUE TITLE
Thanks and License

### ISSUE THREAD

**Issue by eddiemonge** [kunokdev/cra-runtime-environment-variables#2]
Thanks for doing this. 

Can you add a license to this project (hopefully MIT or something similar) so it can be used in projects?

**Comment by kunokdev** [comment]
Sure, I will add MIT license through the day.

**Comment by kunokdev** [comment]
MIT license is now [added](https://github.com/kunokdev/cra-runtime-environment-variables/commit/21fc6ffcdc75a81fb705e868f8a94b15a224c67e).
